# Generated by Django 4.1.7 on 2023-04-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('temp', models.IntegerField()),
                ('joined_date', models.DateTimeField()),
            ],
        ),
    ]
