# Generated by Django 4.1.7 on 2023-04-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_check',
            name='joined_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='weather_check',
            name='temp',
            field=models.IntegerField(null=True),
        ),
    ]
